interface Countries {
  [key: string]: string[];
}
const countries: Countries = {
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "La Plata",
    "Mar del Plata",
    "Mendoza",
    "Rosario",
    "Salta",
    "San Juan",
    "San Miguel de Tucumán",
    "Santa Fe",
  ],
  Armenia: [
    "Abovyan",
    "Artashat",
    "Gavar",
    "Gyumri",
    "Hrazdan",
    "Kapan",
    "Sevan",
    "Vanadzor",
    "Yerevan",
  ],
  Australia: [
    "Adelaide",
    "Brisbane",
    "Canberra",
    "Gold Coast",
    "Logan City",
    "Melbourne",
    "Newcastle",
    "Perth",
    "Sydney",
    "Wollongong",
  ],
  Azerbaijan: [
    "Baku",
    "Ganja",
    "Khirdalan",
    "Lankaran",
    "Mingachevir",
    "Nakhchivan",
    "Shaki",
    "Shirvan",
    "Sumqayit",
    "Yevlakh",
  ],
  Belarus: [
    "Baranovichi",
    "Barysaw",
    "Brest",
    "Gomel",
    "Hrodna",
    "Minsk",
    "Mogilev",
    "Orsha",
    "Pinsk",
    "Vitebsk",
  ],
  Brazil: [
    "Brasília",
    "Belo Horizonte",
    "Curitiba",
    "Fortaleza",
    "Manaus",
    "Porto Alegre",
    "Recife",
    "Rio de Janeiro",
    "Salvador",
    "São Paulo",
  ],
  Canada: [
    "Calgary",
    "Edmonton",
    "Hamilton",
    "Kitchener",
    "Montreal",
    "Ottawa",
    "Quebec City",
    "Toronto",
    "Vancouver",
    "Winnipeg",
  ],
  China: [
    "Beijing",
    "Chengdu",
    "Chongqing",
    "Guangzhou",
    "Nanjing",
    "Shanghai",
    "Shenzhen",
    "Tianjin",
    "Wuhan",
    "Xi'an",
  ],
  Colombia: [
    "Barranquilla",
    "Bogotá",
    "Bucaramanga",
    "Cali",
    "Cartagena",
    "Cúcuta",
    "Ibagué",
    "Medellín",
    "Pereira",
    "Santa Marta",
  ],
  France: [
    "Bordeaux",
    "Lille",
    "Lyon",
    "Marseille",
    "Montpellier",
    "Nantes",
    "Nice",
    "Paris",
    "Strasbourg",
    "Toulouse",
  ],
  Germany: [
    "Berlin",
    "Cologne",
    "Dortmund",
    "Düsseldorf",
    "Essen",
    "Frankfurt",
    "Hamburg",
    "Leipzig",
    "Munich",
    "Stuttgart",
  ],
  India: [
    "Ahmedabad",
    "Bangalore",
    "Chennai",
    "Delhi",
    "Hyderabad",
    "Jaipur",
    "Kolkata",
    "Mumbai",
    "Pune",
    "Surat",
  ],
  Indonesia: [
    "Bandung",
    "Bekasi",
    "Depok",
    "Jakarta",
    "Makassar",
    "Medan",
    "Palembang",
    "Semarang",
    "Surabaya",
    "Tangerang",
  ],
  Italy: [
    "Bari",
    "Bologna",
    "Catania",
    "Florence",
    "Genoa",
    "Milan",
    "Naples",
    "Palermo",
    "Rome",
    "Turin",
  ],
  Japan: [
    "Fukuoka",
    "Kawasaki",
    "Kobe",
    "Kyoto",
    "Nagoya",
    "Osaka",
    "Saitama",
    "Sapporo",
    "Tokyo",
    "Yokohama",
  ],
  Kazakhstan: [
    "Almaty",
    "Aktobe",
    "Atyrau",
    "Karaganda",
    "Kostanay",
    "Nur-Sultan",
    "Oskemen",
    "Pavlodar",
    "Semey",
    "Shymkent",
  ],
  Kenya: [
    "Eldoret",
    "Garissa",
    "Kakamega",
    "Kisumu",
    "Kitale",
    "Malindi",
    "Mombasa",
    "Nairobi",
    "Nakuru",
    "Thika",
  ],
  Malaysia: [
    "George Town",
    "Ipoh",
    "Johor Bahru",
    "Kota Kinabalu",
    "Kuala Lumpur",
    "Kuantan",
    "Malacca City",
    "Petaling Jaya",
    "Shah Alam",
    "Kuching",
  ],
  Mexico: [
    "Ciudad Juárez",
    "Guadalajara",
    "León",
    "Mexico City",
    "Monterrey",
    "Puebla",
    "Querétaro",
    "San Luis Potosí",
    "Tijuana",
    "Zapopan",
  ],
  Netherlands: [
    "Almere",
    "Amsterdam",
    "Breda",
    "Eindhoven",
    "Groningen",
    "Nijmegen",
    "Rotterdam",
    "The Hague",
    "Tilburg",
    "Utrecht",
  ],
  Nigeria: [
    "Aba",
    "Abuja",
    "Benin City",
    "Ibadan",
    "Kano",
    "Kaduna",
    "Lagos",
    "Maiduguri",
    "Port Harcourt",
    "Zaria",
  ],
  Pakistan: [
    "Faisalabad",
    "Gujranwala",
    "Karachi",
    "Lahore",
    "Multan",
    "Peshawar",
    "Quetta",
    "Rawalpindi",
    "Sargodha",
    "Sialkot",
  ],
  Philippines: [
    "Antipolo",
    "Cagayan de Oro",
    "Caloocan",
    "Cebu City",
    "Davao City",
    "Manila",
    "Pasig",
    "Quezon City",
    "Taguig",
    "Zamboanga City",
  ],
  Russia: [
    "Chelyabinsk",
    "Kazan",
    "Moscow",
    "Nizhny Novgorod",
    "Novosibirsk",
    "Omsk",
    "Rostov-on-Don",
    "Saint Petersburg",
    "Ufa",
    "Yekaterinburg",
  ],
  SouthAfrica: [
    "Benoni",
    "Bloemfontein",
    "Cape Town",
    "Durban",
    "East London",
    "Johannesburg",
    "Pietermaritzburg",
    "Port Elizabeth",
    "Pretoria",
    "Soweto",
  ],
  SouthKorea: [
    "Busan",
    "Changwon",
    "Daegu",
    "Daejeon",
    "Goyang",
    "Gwangju",
    "Incheon",
    "Seoul",
    "Suwon",
    "Ulsan",
  ],
  Spain: [
    "Barcelona",
    "Bilbao",
    "Las Palmas",
    "Madrid",
    "Málaga",
    "Murcia",
    "Palma",
    "Seville",
    "Valencia",
    "Zaragoza",
  ],
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Hat Yai",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Nakhon Si Thammarat",
    "Nonthaburi",
    "Pak Kret",
    "Ubon Ratchathani",
    "Udon Thani",
  ],
  Turkey: [
    "Adana",
    "Ankara",
    "Antalya",
    "Bursa",
    "Diyarbakir",
    "Gaziantep",
    "Istanbul",
    "Izmir",
    "Konya",
    "Mersin",
  ],
  UAE: [
    "Abu Dhabi",
    "Ajman",
    "Al Ain",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al-Quwain",
  ],
  Ukraine: [
    "Dnipro",
    "Donetsk",
    "Kharkiv",
    "Kryvyi Rih",
    "Kyiv",
    "Lviv",
    "Mariupol",
    "Mykolaiv",
    "Odessa",
    "Zaporizhzhia",
  ],
  UK: [
    "Birmingham",
    "Bristol",
    "Edinburgh",
    "Glasgow",
    "Leeds",
    "Leicester",
    "Liverpool",
    "London",
    "Manchester",
    "Sheffield",
  ],
  USA: [
    "Chicago",
    "Dallas",
    "Houston",
    "Los Angeles",
    "New York",
    "Philadelphia",
    "Phoenix",
    "San Antonio",
    "San Diego",
    "San Jose",
  ],
  Uzbekistan: [
    "Andijan",
    "Bukhara",
    "Fergana",
    "Jizzakh",
    "Kokand",
    "Namangan",
    "Nukus",
    "Qarshi",
    "Samarkand",
    "Tashkent",
  ],
  Vietnam: [
    "Bien Hoa",
    "Can Tho",
    "Da Nang",
    "Hai Phong",
    "Hanoi",
    "Ho Chi Minh City",
    "Hue",
    "Nha Trang",
    "Thanh Hoa",
    "Vung Tau",
  ],
  Kyrgyzstan: [
    "Bishkek",
    "Osh",
    "Jalal-Abad",
    "Karakol",
    "Tokmok",
    "Uzgen",
    "Talas",
    "Naryn",
    "Balykchy",
    "Kara-Balta",
  ],
  Moldova: [
    "Chișinău",
    "Tiraspol",
    "Bălți",
    "Bender (Tighina)",
    "Rîbnița",
    "Cahul",
    "Ungheni",
    "Soroca",
    "Orhei",
    "Dubăsari",
  ],
  Bali: [
    "Denpasar",
    "Kuta",
    "Ubud",
    "Seminyak",
    "Sanur",
    "Nusa Dua",
    "Canggu",
    "Jimbaran",
    "Uluwatu",
    "Lovina",
  ],
};

export default countries;
